language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.0.0
solution: KloudCodingChallenge.sln
script:
  - cd KloudCodingChallenge
  - dotnet restore
  - dotnet build -c Release
  - dotnet test KloudCodingChallenge.Test/KloudCodingChallenge.Test.csproj
notifications:
  email:
    - lingalamanojreddy@outlook.com